[files]
extend-exclude = [
    "framework/examples/myproject_cll/README.md",
    "framework/components/blockchain/tron.go",
    "tools/flakeguard/e2e-flaky-test-guide.md",
    "infra/**",
    "book/**",
    "**/go.mod",
    "**/go.sum",
    "charts",
    "**/*.tgz",
    "**/*.png",
    "wasp/HOW_IT_WORKS.md",
    "wasp/dashboard/**",
    "seth/*_test.go",
    "seth/dot_graph.go"
]