[fakes]
  # Fake service image, usually can be found in our ECR with $project-fakes name
  image = ''
  # The port which Docker container is exposing
  port = 0

  # Fakes service config output
  [fakes.out]
    # Whether to respect caching or not, if cache = true component won't be deployed again
    use_cache = false
    # Base URL which can be used when running locally
    base_url_host = ''
    # Base URL to reach fakes service from other Docker containers
    base_url_docker = ''

    # Kubernetes service spec used to connect locally
    [fakes.out.k8s_service]
      Kind = ''
      APIVersion = ''
      Name = ''
      GenerateName = ''
      Namespace = ''
      SelfLink = ''
      UID = ''
      ResourceVersion = ''
      Generation = 0
      CreationTimestamp = '0001-01-01T00:00:00Z'
      DeletionTimestamp = '0001-01-01T00:00:00Z'
      DeletionGracePeriodSeconds = 0
      Finalizers = []

      [fakes.out.k8s_service.Labels]

      [fakes.out.k8s_service.Annotations]

      [[fakes.out.k8s_service.OwnerReferences]]
        APIVersion = ''
        Kind = ''
        Name = ''
        UID = ''
        Controller = false
        BlockOwnerDeletion = false

      [[fakes.out.k8s_service.ManagedFields]]
        Manager = ''
        Operation = ''
        APIVersion = ''
        Time = '0001-01-01T00:00:00Z'
        FieldsType = ''
        Subresource = ''

        [fakes.out.k8s_service.ManagedFields.FieldsV1]
          Raw = []

      [fakes.out.k8s_service.Spec]
        ClusterIP = ''
        ClusterIPs = []
        Type = ''
        ExternalIPs = []
        SessionAffinity = ''
        LoadBalancerIP = ''
        LoadBalancerSourceRanges = []
        ExternalName = ''
        ExternalTrafficPolicy = ''
        HealthCheckNodePort = 0
        PublishNotReadyAddresses = false
        IPFamilies = []
        IPFamilyPolicy = ''
        AllocateLoadBalancerNodePorts = false
        LoadBalancerClass = ''
        InternalTrafficPolicy = ''
        TrafficDistribution = ''

        [[fakes.out.k8s_service.Spec.Ports]]
          Name = ''
          Protocol = ''
          AppProtocol = ''
          Port = 0
          NodePort = 0

          [fakes.out.k8s_service.Spec.Ports.TargetPort]
            Type = 0
            IntVal = 0
            StrVal = ''

        [fakes.out.k8s_service.Spec.Selector]

        [fakes.out.k8s_service.Spec.SessionAffinityConfig]
          [fakes.out.k8s_service.Spec.SessionAffinityConfig.ClientIP]
            TimeoutSeconds = 0

      [fakes.out.k8s_service.Status]
        [fakes.out.k8s_service.Status.LoadBalancer]
          [[fakes.out.k8s_service.Status.LoadBalancer.Ingress]]
            IP = ''
            Hostname = ''
            IPMode = ''

            [[fakes.out.k8s_service.Status.LoadBalancer.Ingress.Ports]]
              Port = 0
              Protocol = ''
              Error = ''

        [[fakes.out.k8s_service.Status.Conditions]]
          Type = ''
          Status = ''
          ObservedGeneration = 0
          LastTransitionTime = '0001-01-01T00:00:00Z'
          Reason = ''
          Message = ''
