metadata:
  name: dummy-adapter
spec:
  selector:
    matchlabels:
      app: dummy-adapter
  template:
    metadata:
      labels:
        app: dummy-adapter
    spec:
      containers:
        - name: dummy-adapter
          image: kalverra/dummy-external-adapter
          ports:
            - containerPort: {{ .Values.adapter.apiPort }}
          readinessProbe:
            httpGet:
              path: /
              port: 6060
            periodSeconds: 2
          resources:
            requests:
              memory: {{ .Config.Apps.Adapter.Requests.Memory }}
              cpu: {{ .Config.Apps.Adapter.Requests.Cpu }}
            limits:
              memory: {{ .Config.Apps.Adapter.Limits.Memory }}
              cpu: {{ .Config.Apps.Adapter.Limits.Cpu }}
