metadata:
  name: explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    objectmeta:
      labels:
        app: explorer
    spec:
      volumes:
        - name: kafka-tls
          secret:
            secretName: kafka-tls
      containers:
        - name: explorer
          command:
            - yarn
            - workspace
            - '@chainlink/explorer'
            - run
            - prod
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: 0
            - name: PGPASSWORD
              value: explorer
            - name: EXPLORER_COOKIE_SECRET
              value: "testingtestingtestingtestingtesting"
            - name: EXPLORER_ADMIN_USERNAME
              value: "admin"
            - name: EXPLORER_ADMIN_PASSWORD
              value: "password"
            - name: TYPEORM_PASSWORD
              value: explorer
            - name: TYPEORM_HOST
              value: 127.0.0.1
            - name: TYPEORM_PORT
              value: 5432
            - name: TYPEORM_DATABASE
              value: explorer_production
            - name: TYPEORM_USERNAME
              value: postgres
            - name: LOG_LEVEL
              value: debug
            #             Kafka settings
            - name: EXPLORER_KAFKA_BROKERS
              value: {{ .Values.KafkaGroup.kafka.clusterURL }}
            - name: EXPLORER_KAFKA_CLIENT_ID
              value: "explorer"
            - name: EXPLORER_KAFKA_TOPIC
              value: "ocr-telemetry-v0"
            - name: EXPLORER_KAFKA_CONNECTION_TIMEOUT
              value: 60000
            - name: EXPLORER_KAFKA_REQUEST_TIMEOUT
              value: 30000
            - name: EXPLORER_KAFKA_INITIAL_RETRY_TIME
              value: 300
            - name: EXPLORER_KAFKA_RETRIES
              value: 5
          image: 'smartcontract/explorer:candidate-0.9.20-archive'
          volumeMounts:
            - name: kafka-tls
              mountPath: /etc/ssl/certs/kafka-0.keystore.pem
              subPath: kafka-0.keystore.pem
              readOnly: false
            - name: kafka-tls
              mountPath: /etc/ssl/certs/kafka.truststore.pem
              subPath: kafka.truststore.pem
              readOnly: false
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 9080
            - containerPort: 9081
          resources:
            requests:
              memory: "1Gi"
              cpu: "2"
            limits:
              memory: "1Gi"
              cpu: "2"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 5
        - name: chainlink-explorer-db
          image: postgres:11.6
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1024m"
          env:
            - name: POSTGRES_DB
              value: explorer_production
              valuefrom: null
            - name: POSTGRES_PASSWORD
              value: explorer
              valuefrom: null
            - name: PGPASSWORD
              value: explorer
              valuefrom: null
            - name: PGUSER
              value: postgres
              valuefrom: null
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 2
            periodSeconds: 2