metadata:
  name: {{ .Network.Name }}
spec:
  template:
    spec:
      volumes:
      - name: configmap-volume
        configMap:
          name: {{ .Network.Name }}
      containers:
      - name: geth-network
        image: {{ .Config.Apps.Geth.Image }}:{{ .Config.Apps.Geth.Version }}
        entrypoint: sh ./root/init.sh
        volumeMounts:
        - name: configmap-volume
          mountPath: /root/config
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key1
          subPath: key1
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key2
          subPath: key2
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key3
          subPath: key3
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key4
          subPath: key4
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key5
          subPath: key5
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key6
          subPath: key6
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key7
          subPath: key7
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key8
          subPath: key8
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key9
          subPath: key9
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key10
          subPath: key10
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key11
          subPath: key11
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key12
          subPath: key12
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key13
          subPath: key13
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key14
          subPath: key14
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key15
          subPath: key15
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key16
          subPath: key16
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key17
          subPath: key17
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key18
          subPath: key18
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key19
          subPath: key19
        - name: configmap-volume
          mountPath: /root/.ethereum/devchain/keystore/key20
          subPath: key20
        args:
          - --dev
          - --dev.period
          - 1
          - --password
          - /root/config/password.txt
          - --datadir
          - /root/.ethereum/devchain
          - --unlock
          - 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
          - --unlock
          - 0x70997970C51812dc3A010C7d01b50e0d17dc79C8
          - --unlock
          - 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
          - --unlock
          - 0x90F79bf6EB2c4f870365E785982E1f101E93b906
          - --unlock
          - 0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65
          - --unlock
          - 0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc
          - --unlock
          - 0x976EA74026E726554dB657fA54763abd0C3a0aa9
          - --unlock
          - 0x14dC79964da2C08b23698B3D3cc7Ca32193d9955
          - --unlock
          - 0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f
          - --unlock
          - 0xa0Ee7A142d267C1f36714E4a8F75612F20a79720
          - --unlock
          - 0xBcd4042DE499D14e55001CcbB24a551F3b954096
          - --unlock
          - 0x71bE63f3384f5fb98995898A86B02Fb2426c5788
          - --unlock
          - 0xFABB0ac9d68B0B445fB7357272Ff202C5651694a
          - --unlock
          - 0x1CBd3b2770909D4e10f157cABC84C7264073C9Ec
          - --unlock
          - 0xdF3e18d64BC6A983f673Ab319CCaE4f1a57C7097
          - --unlock
          - 0xcd3B766CCDd6AE721141F452C550Ca635964ce71
          - --unlock
          - 0x2546BcD3c84621e976D8185a91A922aE77ECEc30
          - --unlock
          - 0xbDA5747bFD65F08deb54cb465eB87D40e51B197E
          - --unlock
          - 0xdD2FD4581271e230360230F9337D5c0430Bf44C0
          - --unlock
          - 0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199
          - --networkid={{ .Network.ChainID }}
          - --mine
          - --miner.threads
          - 1
          - --miner.gasprice
          - 10000000000
          - --miner.gastarget
          - {{ .Network.BlockGasLimit }}
          - --miner.etherbase
          - 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
          - --rpcapi="admin,debug,web3,eth,txpool,personal,clique,miner,net"
          - --ipcdisable
          - --http
          - --http.addr
          - 0.0.0.0
          - --http.port=8544
          - --ws
          - --ws.origins
          - "*"
          - --ws.addr
          - 0.0.0.0
          - --ws.port={{ .Network.RPCPort }}
          - --graphql
          - --graphql.corsdomain
          - "*"
          - --allow-insecure-unlock
          - --rpc.allow-unprotected-txs
          - --http.corsdomain
          - "*"
          - --vmdebug
        ports:
        - containerPort: {{ .Network.RPCPort }}
        resources:
          requests:
            memory: {{ .Config.Apps.Geth.Requests.Memory }}
            cpu: {{ .Config.Apps.Geth.Requests.Cpu }}
          limits:
            memory: {{ .Config.Apps.Geth.Limits.Memory }}
            cpu: {{ .Config.Apps.Geth.Limits.Cpu }}

