metadata:
  name: otpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otpe
  template:
    objectmeta:
      labels:
        app: otpe
    spec:
      containers:
        - name: otpe
          env:
            - name: KAFKA_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_BROKERS
              value: {{ .Values.KafkaGroup.kafka.clusterURL }}
            - name: KAFKA_TOPIC
              value: "ocr-telemetry-v0"
            - name: KAFKA_CLIENT_ID
              value: "explorer"
            - name: KAFKA_GROUP_ID
              value: "explorer"
            - name: RPC_URL
              value: {{ if .Values.DependencyGroup.ethereum_geth_0.clusterURL }}{{ .Values.DependencyGroup.ethereum_geth_0.clusterURL }}{{ else if .Values.DependencyGroup.ethereum_geth_performance_0.clusterURL }}{{ .Values.DependencyGroup.ethereum_geth_performance_0.clusterURL }}{{ else if .Values.DependencyGroup.ethereum_ganache_0.clusterURL }}{{ .Values.DependencyGroup.ethereum_ganache_0.clusterURL }}{{ else if .Values.DependencyGroup.ethereum_hardhat_0.clusterURL }}{{ .Values.DependencyGroup.ethereum_hardhat_0.clusterURL }}{{ end }}
            - name: METRICS_ENDPOINT
              value: ":1337"
            - name: WEIWATCHERS_NODES_URL
              value: {{ .Values.MockserverDependencyGroup.mockserver.nodesURL }}
            - name: WEIWATCHERS_CHAINMONITOR_URL
              value: {{ .Values.MockserverDependencyGroup.mockserver.contractsURL }}
            - name: CHAIN_TYPE
              value: eth
            - name: LOG_LEVEL
              value: debug
          image: {{ .Config.Apps.Otpe.Image }}:{{ .Config.Apps.Otpe.Version }}
          ports:
            - containerPort: 1337
          resources:
            requests:
              memory: {{ .Config.Apps.Otpe.Requests.Memory }}
              cpu: {{ .Config.Apps.Otpe.Requests.Cpu }}
            limits:
              memory: {{ .Config.Apps.Otpe.Limits.Memory }}
              cpu: {{ .Config.Apps.Otpe.Limits.Cpu }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: 1337
            initialDelaySeconds: 50
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: 1337
            initialDelaySeconds: 25
            periodSeconds: 5