# Retains default and configurable name-values for the integration framework
#
# All configuration can be set at runtime with environment variables, for example:
# KEEP_ENVIRONMENTS=OnFail
# APPS_CHAINLINK_VERSION=1.0.0

network: "ethereum_geth" # Selected network for test execution
keep_environments: Never # Options: Always, OnFail, Never

apps:
  chainlink:
    image: public.ecr.aws/chainlink/chainlink
    version: 0.10.12
    requests:
      memory: 768Mi
      cpu: 300m
    limits:
      memory: 1024Mi
      cpu: 450m
  postgres:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1024Mi
      cpu: 350m
  geth:
    requests:
      memory: 1536Mi
      cpu: 250m
    limits:
      memory: 2048Mi
      cpu: 375m
  adapter:
    requests:
      memory: 64Mi
      cpu: 25m
    limits:
      memory: 96Mi
      cpu: 50m

private_keys: &private_keys
  private_keys:
    - ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    - 59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
    - 5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a

secret_private_keys_default: &secret_private_keys_default
  secret_private_keys: false

namespace_for_secret_default: &namespace_for_secret_default
  namespace_for_secret: default

networks:
  ethereum_geth:
    name: "Ethereum Geth dev"
    chain_id: 1337
    type: evm
    <<: *secret_private_keys_default
    <<: *namespace_for_secret_default
    <<: *private_keys
    transaction_limit: 9500000
    transaction_timeout: 10s
    minimum_confirmations: 1
    gas_estimation_buffer: 100000
    block_gas_limit: 40000000
retry:
  attempts: 20
  linear_delay: 1s

kubernetes:
  # Increase k8s default throttling variables to avoid test slowdown
  qps: 50
  burst: 50
  # How long to wait for the environment to deploy & be marked as healthy before test errors
  deployment_timeout: 3m

logging:
  # panic=5, fatal=4, error=3, warn=2, info=1, debug=0, trace=-1
  level: 0
prometheus:
  url: ""
