{{/* Prysm Beacon Chain Deployment */}}
{{- define "eth2-common.templates.deployment.prysm-beacon" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.prysm.beacon.name }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.prysm.beacon.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.prysm.beacon.name }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: release
                operator: In
                values:
                - {{ .Release.Name }}
            topologyKey: kubernetes.io/hostname
      nodeSelector:
        eth2: "true"
      volumes:
      - name: {{ .Release.Name }}-chain-state
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Values.storage.claim }}
      - name: {{ .Release.Name }}-after-genesis-helper-config
        configMap:
          name: {{ .Release.Name }}-after-genesis-helper-config
      containers:
        - name: {{ .Values.prysm.beacon.name }}
          image: {{ .Values.prysm.beacon.image.repository }}:{{ .Values.prysm.beacon.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - "--accept-terms-of-use"
            - "--datadir=/consensus-data-chain"
            - "--genesis-state={{ .Values.shared.configDataDir }}/genesis.ssz"
            - "--chain-config-file={{ .Values.shared.configDataDir }}/config.yaml"
            - "--contract-deployment-block=0"
            - "--chain-id={{ .Values.general.networkId }}"
            - "--rpc-host=0.0.0.0"
            - "--grpc-gateway-host=0.0.0.0"
            - "--grpc-gateway-corsdomain=*"
            - "--execution-endpoint=http://{{ .Release.Name }}-{{ .Values.excutionClient.name }}-svc:{{ .Values.excutionClient.ports.execution }}"
            - "--jwt-secret={{ .Values.shared.configDataDir }}/{{ .Values.shared.jwtFile }}"
            - "--subscribe-all-subnets=true"
            - "--suggested-fee-recipient={{ .Values.prysm.shared.feeRecipent }}"
            - "--minimum-peers-per-subnet=0"
            - "--min-sync-peers=0"
            - "--force-clear-db"
            - "--interop-eth1data-votes"
          ports:
            - name: query-rpc
              containerPort: {{ .Values.prysm.beacon.ports.query }}
            - name: node-rpc
              containerPort: {{ .Values.prysm.beacon.ports.node }}
            - name: status
              containerPort: {{ .Values.prysm.beacon.ports.status }}
          volumeMounts:
            - name: {{ .Release.Name }}-chain-state
              mountPath: /data

{{- include "eth2-common.templates.consensus-client.init-containers" . | nindent 6 }}
{{- end}}