# Just a config for unit testing
keep_environments: Always
private_keys: &private_keys
    private_keys:
networks:
    test_this_get:
        name: "Tester Ted"
        chain_id: 1337
        type: evm
        <<: *private_keys
        transaction_limit: 1
        transaction_timeout: 11s
        minimum_confirmations: 1
        gas_estimation_buffer: 1
        block_gas_limit: 1
