imagePullPolicy: IfNotPresent

bootnode:
  replicaCount: 2
  image:
    repository: ethereum/client-go
    tag: alltools-v1.10.6

bootnodeRegistrar:
  replicaCount: 1
  image:
    repository: jpoon/bootnode-registrar
    tag: v1.0.0

geth:
  image:
    repository: ethereum/client-go
    tag: v1.10.6
  tx:
    replicaCount: 1
    service:
      type: ClusterIP
  miner:
    replicaCount: 2
    account:
      secret: ""
  genesis:
    networkId: 1337

