apiVersion: v1
data:
  init.sql: |
    CREATE DATABASE relay_1;
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    app: postgres
  name: postgres-cm0-relay-{{ .Values.idx }}
