[book]
authors = ["skudasov"]
language = "en"
multilingual = false
src = "src"
title = "Chainlink Testing Framework"

[build]
build-dir = "docs"

[output.html]
default-theme = "ayu"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.alerts]
[preprocessor.cmdrun]

[preprocessor.mermaid]
command = "mdbook-mermaid"
