apiVersion: v2
description: Eth2 private network with Geth and Prysm
name: geth-prysm
version: 0.2.0
dependencies:
  - name: eth2-common
    version: 0.5.0
    repository: 'https://raw.githubusercontent.com/smartcontractkit/qa-charts/gh-pages/'
