name: Framework Golden Tests Examples
on:
  push:

jobs:
  test:
    defaults:
      run:
        working-directory: framework/examples/myproject
    env:
      LOKI_TENANT_ID: promtail
      LOKI_URL: http://localhost:3030/loki/api/v1/push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        test:
          - name: TestSmoke
            config: smoke.toml
            count: 1
            timeout: 10m
          - name: TestLoad
            config: load.toml
            count: 1
            timeout: 10m
          - name: TestChaos
            config: chaos.toml
            count: 1
            timeout: 10m
    steps:
      - name: Checkout repo
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.PUBLIC_AWS_ECR_ROLE }}
          aws-region: us-east-1
      - name: Authenticate to ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registry-type: public
      - name: Check for changes in Framework
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            src:
              - 'framework/**'
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.8
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-modules-${{ hashFiles('**/go.sum') }}-${{ runner.os }}-framework-golden-examples
          restore-keys: |
            go-modules-${{ runner.os }}-framework-golden-examples
            go-modules-${{ runner.os }}
      - name: Install dependencies
        run: go mod download
      - name: Run Docker Component Tests
        if: steps.changes.outputs.src == 'true'
        env:
          CTF_CONFIGS: ${{ matrix.test.config }}
        run: |
          go test -timeout ${{ matrix.test.timeout }} -v -count ${{ matrix.test.count }} -run ${{ matrix.test.name }}
